package view;

/**
 *
 * @author fabiano
 */
public class telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaprincipal
     */
    public telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jspPrincipal = new javax.swing.JScrollPane();
        jpPainelPrincipal = new javax.swing.JPanel();
        jpPrinlMonit = new javax.swing.JPanel();
        jtMonitoramento = new javax.swing.JTabbedPane();
        jpMonitoramento = new javax.swing.JPanel();
        jdpMonitoramento = new javax.swing.JDesktopPane();
        jifMonitoramento = new javax.swing.JInternalFrame();
        jifEventoSelecionado = new javax.swing.JInternalFrame();
        lbevento = new javax.swing.JLabel();
        lbRecepcao = new javax.swing.JLabel();
        lbAtendimento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jifEventos = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jpCentrais = new javax.swing.JPanel();
        jdpCentrais = new javax.swing.JDesktopPane();
        jtpCentrais = new javax.swing.JTabbedPane();
        jpDadosCentrais = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpPesquisa = new javax.swing.JPanel();
        jlPesquisaPor = new javax.swing.JLabel();
        jcbFiltrarPor = new javax.swing.JComboBox<>();
        jlDescricaoPesquisa = new javax.swing.JLabel();
        jtfDescricaoConsulta = new javax.swing.JTextField();
        jlTipoPesquisa = new javax.swing.JLabel();
        jcbTipoPesquisa = new javax.swing.JComboBox<>();
        jtfFiltroPesquisa = new javax.swing.JTextField();
        jtbPesquisar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPesquisa = new javax.swing.JTable();
        jpRelatorio = new javax.swing.JPanel();
        jpConfiguracao = new javax.swing.JPanel();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 153, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameprincipal"); // NOI18N

        jspPrincipal.setPreferredSize(new java.awt.Dimension(1234, 545));

        jpPainelPrincipal.setBackground(new java.awt.Color(102, 102, 255));
        jpPainelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 153, 255), new java.awt.Color(153, 153, 153), null));
        jpPainelPrincipal.setLayout(new java.awt.BorderLayout());

        jpPrinlMonit.setPreferredSize(new java.awt.Dimension(766, 545));

        jtMonitoramento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 102, 255), null, null));
        jtMonitoramento.setMinimumSize(new java.awt.Dimension(600, 545));
        jtMonitoramento.setName("JTabbedPanel"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtMonitoramento, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), jtMonitoramento, org.jdesktop.beansbinding.BeanProperty.create("preferredSize"));
        bindingGroup.addBinding(binding);

        jpMonitoramento.setPreferredSize(new java.awt.Dimension(839, 545));

        jdpMonitoramento.setBackground(new java.awt.Color(204, 204, 204));
        jdpMonitoramento.setName(""); // NOI18N
        jdpMonitoramento.setPreferredSize(new java.awt.Dimension(1211, 610));
        jdpMonitoramento.setRequestFocusEnabled(false);

        jifMonitoramento.setFrameIcon(null);
        jifMonitoramento.setMinimumSize(new java.awt.Dimension(38, 200));
        jifMonitoramento.setPreferredSize(new java.awt.Dimension(572, 608));
        jifMonitoramento.setVisible(true);

        jifEventoSelecionado.setTitle("Evento Selecionado");
        jifEventoSelecionado.setToolTipText("");
        jifEventoSelecionado.setVisible(true);

        lbevento.setText("Evento: ");

        lbRecepcao.setText("Recepção via: ");

        lbAtendimento.setText("Atendimento: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("---- ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("----");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("----");

        jLabel4.setText("Descrição: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("----");

        javax.swing.GroupLayout jifEventoSelecionadoLayout = new javax.swing.GroupLayout(jifEventoSelecionado.getContentPane());
        jifEventoSelecionado.getContentPane().setLayout(jifEventoSelecionadoLayout);
        jifEventoSelecionadoLayout.setHorizontalGroup(
            jifEventoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifEventoSelecionadoLayout.createSequentialGroup()
                .addGroup(jifEventoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jifEventoSelecionadoLayout.createSequentialGroup()
                        .addComponent(lbevento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lbRecepcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifEventoSelecionadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAtendimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jifEventoSelecionadoLayout.setVerticalGroup(
            jifEventoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifEventoSelecionadoLayout.createSequentialGroup()
                .addGroup(jifEventoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbevento)
                    .addComponent(lbRecepcao)
                    .addComponent(lbAtendimento)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifEventoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 400, Short.MAX_VALUE))
        );

        jifEventos.setTitle("Eventos");
        jifEventos.setVisible(true);

        javax.swing.GroupLayout jifEventosLayout = new javax.swing.GroupLayout(jifEventos.getContentPane());
        jifEventos.getContentPane().setLayout(jifEventosLayout);
        jifEventosLayout.setHorizontalGroup(
            jifEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifEventosLayout.setVerticalGroup(
            jifEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jifMonitoramentoLayout = new javax.swing.GroupLayout(jifMonitoramento.getContentPane());
        jifMonitoramento.getContentPane().setLayout(jifMonitoramentoLayout);
        jifMonitoramentoLayout.setHorizontalGroup(
            jifMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jifEventoSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jifEventos)
        );
        jifMonitoramentoLayout.setVerticalGroup(
            jifMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifMonitoramentoLayout.createSequentialGroup()
                .addComponent(jifEventoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jifEventos)
                .addGap(35, 35, 35))
        );

        try {
            jifEventoSelecionado.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrame2.setMinimumSize(new java.awt.Dimension(38, 608));
        jInternalFrame2.setPreferredSize(new java.awt.Dimension(613, 608));
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jdpMonitoramento.setLayer(jifMonitoramento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpMonitoramento.setLayer(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpMonitoramentoLayout = new javax.swing.GroupLayout(jdpMonitoramento);
        jdpMonitoramento.setLayout(jdpMonitoramentoLayout);
        jdpMonitoramentoLayout.setHorizontalGroup(
            jdpMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpMonitoramentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jifMonitoramento, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpMonitoramentoLayout.setVerticalGroup(
            jdpMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpMonitoramentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdpMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jifMonitoramento, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(jdpMonitoramentoLayout.createSequentialGroup()
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jpMonitoramentoLayout = new javax.swing.GroupLayout(jpMonitoramento);
        jpMonitoramento.setLayout(jpMonitoramentoLayout);
        jpMonitoramentoLayout.setHorizontalGroup(
            jpMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMonitoramento, javax.swing.GroupLayout.DEFAULT_SIZE, 1231, Short.MAX_VALUE)
        );
        jpMonitoramentoLayout.setVerticalGroup(
            jpMonitoramentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMonitoramentoLayout.createSequentialGroup()
                .addComponent(jdpMonitoramento, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jtMonitoramento.addTab("Monitoramento", null, jpMonitoramento, "");

        jpCentrais.setPreferredSize(new java.awt.Dimension(839, 545));

        jdpCentrais.setPreferredSize(new java.awt.Dimension(1211, 655));
        jdpCentrais.setRequestFocusEnabled(false);

        jtpCentrais.setMinimumSize(new java.awt.Dimension(0, 0));
        jtpCentrais.setPreferredSize(new java.awt.Dimension(1211, 610));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1211, 655));

        javax.swing.GroupLayout jpDadosCentraisLayout = new javax.swing.GroupLayout(jpDadosCentrais);
        jpDadosCentrais.setLayout(jpDadosCentraisLayout);
        jpDadosCentraisLayout.setHorizontalGroup(
            jpDadosCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        jpDadosCentraisLayout.setVerticalGroup(
            jpDadosCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        jtpCentrais.addTab("Dados Equipamento", jpDadosCentrais);

        jlPesquisaPor.setText("Pesquisar por: ");

        jcbFiltrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Razão Social", "Nome Fantasia", "Endereço", "Telefone", "CPF", "RG" }));
        jcbFiltrarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrarPorActionPerformed(evt);
            }
        });

        jlDescricaoPesquisa.setText("Descrição da consulta: ");

        jlTipoPesquisa.setText("Tipo de Pesquisa: ");

        jcbTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Que contenha", "Que não contenha", "Seja igual", "Que inicie com" }));
        jcbTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoPesquisaActionPerformed(evt);
            }
        });

        jtbPesquisar.setText("Pesquisar");

        jtPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "ENDEREÇO", "BAIRRO", "CIDADE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPesquisa.setMinimumSize(new java.awt.Dimension(0, 0));
        jtPesquisa.setPreferredSize(new java.awt.Dimension(300, 526));
        jScrollPane1.setViewportView(jtPesquisa);

        javax.swing.GroupLayout jpPesquisaLayout = new javax.swing.GroupLayout(jpPesquisa);
        jpPesquisa.setLayout(jpPesquisaLayout);
        jpPesquisaLayout.setHorizontalGroup(
            jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlPesquisaPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbFiltrarPor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPesquisaLayout.createSequentialGroup()
                        .addComponent(jlDescricaoPesquisa)
                        .addGap(111, 111, 111)
                        .addComponent(jlTipoPesquisa))
                    .addGroup(jpPesquisaLayout.createSequentialGroup()
                        .addComponent(jtfDescricaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTipoPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFiltroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbPesquisar)
                .addContainerGap(463, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jpPesquisaLayout.setVerticalGroup(
            jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisaPor)
                    .addComponent(jlDescricaoPesquisa)
                    .addComponent(jlTipoPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescricaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFiltroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpCentrais.addTab("Pesquisa", jpPesquisa);

        jdpCentrais.setLayer(jtpCentrais, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpCentraisLayout = new javax.swing.GroupLayout(jdpCentrais);
        jdpCentrais.setLayout(jdpCentraisLayout);
        jdpCentraisLayout.setHorizontalGroup(
            jdpCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpCentrais, javax.swing.GroupLayout.DEFAULT_SIZE, 1231, Short.MAX_VALUE)
        );
        jdpCentraisLayout.setVerticalGroup(
            jdpCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpCentrais, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpCentraisLayout = new javax.swing.GroupLayout(jpCentrais);
        jpCentrais.setLayout(jpCentraisLayout);
        jpCentraisLayout.setHorizontalGroup(
            jpCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpCentrais, javax.swing.GroupLayout.DEFAULT_SIZE, 1231, Short.MAX_VALUE)
        );
        jpCentraisLayout.setVerticalGroup(
            jpCentraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpCentrais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtMonitoramento.addTab("Centrais", jpCentrais);

        jpRelatorio.setPreferredSize(new java.awt.Dimension(839, 545));

        javax.swing.GroupLayout jpRelatorioLayout = new javax.swing.GroupLayout(jpRelatorio);
        jpRelatorio.setLayout(jpRelatorioLayout);
        jpRelatorioLayout.setHorizontalGroup(
            jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1231, Short.MAX_VALUE)
        );
        jpRelatorioLayout.setVerticalGroup(
            jpRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        jtMonitoramento.addTab("Relatório", jpRelatorio);

        jpConfiguracao.setPreferredSize(new java.awt.Dimension(850, 545));

        javax.swing.GroupLayout jpConfiguracaoLayout = new javax.swing.GroupLayout(jpConfiguracao);
        jpConfiguracao.setLayout(jpConfiguracaoLayout);
        jpConfiguracaoLayout.setHorizontalGroup(
            jpConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1231, Short.MAX_VALUE)
        );
        jpConfiguracaoLayout.setVerticalGroup(
            jpConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        jtMonitoramento.addTab("Configuração", jpConfiguracao);
        jpConfiguracao.getAccessibleContext().setAccessibleName("");
        jpConfiguracao.getAccessibleContext().setAccessibleParent(jpMonitoramento);

        javax.swing.GroupLayout jpPrinlMonitLayout = new javax.swing.GroupLayout(jpPrinlMonit);
        jpPrinlMonit.setLayout(jpPrinlMonitLayout);
        jpPrinlMonitLayout.setHorizontalGroup(
            jpPrinlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtMonitoramento, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
        );
        jpPrinlMonitLayout.setVerticalGroup(
            jpPrinlMonitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtMonitoramento, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        jtMonitoramento.getAccessibleContext().setAccessibleName("");
        jtMonitoramento.getAccessibleContext().setAccessibleDescription("");

        jpPainelPrincipal.add(jpPrinlMonit, java.awt.BorderLayout.CENTER);

        jspPrincipal.setViewportView(jpPainelPrincipal);

        jmFile.setText("File");
        jmbPrincipal.add(jmFile);

        jmEdit.setText("Edit");
        jmbPrincipal.add(jmEdit);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jspPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbFiltrarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFiltrarPorActionPerformed

    private void jcbTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbFiltrarPor;
    private javax.swing.JComboBox<String> jcbTipoPesquisa;
    private javax.swing.JDesktopPane jdpCentrais;
    private javax.swing.JDesktopPane jdpMonitoramento;
    private javax.swing.JInternalFrame jifEventoSelecionado;
    private javax.swing.JInternalFrame jifEventos;
    private javax.swing.JInternalFrame jifMonitoramento;
    private javax.swing.JLabel jlDescricaoPesquisa;
    private javax.swing.JLabel jlPesquisaPor;
    private javax.swing.JLabel jlTipoPesquisa;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JPanel jpCentrais;
    private javax.swing.JPanel jpConfiguracao;
    private javax.swing.JPanel jpDadosCentrais;
    private javax.swing.JPanel jpMonitoramento;
    private javax.swing.JPanel jpPainelPrincipal;
    private javax.swing.JPanel jpPesquisa;
    private javax.swing.JPanel jpPrinlMonit;
    private javax.swing.JPanel jpRelatorio;
    private javax.swing.JScrollPane jspPrincipal;
    private javax.swing.JTabbedPane jtMonitoramento;
    private javax.swing.JTable jtPesquisa;
    private javax.swing.JToggleButton jtbPesquisar;
    private javax.swing.JTextField jtfDescricaoConsulta;
    private javax.swing.JTextField jtfFiltroPesquisa;
    private javax.swing.JTabbedPane jtpCentrais;
    private javax.swing.JLabel lbAtendimento;
    private javax.swing.JLabel lbRecepcao;
    private javax.swing.JLabel lbevento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
